### ISSUE TITLE
Fallback client side rendering broken?

### ISSUE THREAD

**Issue by magicmark** [airbnb/hypernova-node#15]
When the server is dead, and this clientlib tries to client side render, I get the following error:

`Uncaught TypeError: Cannot read property 'replace' of null`

(I can follow this up with a reproducible example in a repo, but it looks like this is a similar error to this: https://github.com/airbnb/hypernova/issues/52)

I notice that the fallback code currently looks like this:

```
function renderHTML(viewName, data) {
  return `
    <div data-hypernova-key="${viewName}"></div>
    <script type="application/json" data-hypernova-key="${viewName}"><!--${encode(data)}--></script>
  `;
}
```

Whereas in the ruby clientlib, it looks like this:
```
  def render
    <<-HTML
      <div data-hypernova-key="#{key}" data-hypernova-id="#{id}"></div>
      <script type="application/json" data-hypernova-key="#{key}" data-hypernova-id="#{id}"><!--#{encode}--></script>
    HTML
  end
```

(Looks like this lib doesn't yet provide the `data-hypernova-id` attribute)

**Comment by wingleung** [comment]
PR https://github.com/airbnb/hypernova-node/pull/16 is still ongoing, any plans for a new release?
