### ISSUE TITLE
Release v1.1.1.

### ISSUE THREAD

**Issue by sPaCeMoNk3yIam** [airbnb/hypernova-node#41]
Since there was a crucial bug for client side fallback, that got fixed and merged to master already, we need a new release.

**Comment by ljharb** [comment]
You’ve asked in a number of places (https://github.com/airbnb/hypernova-node/pull/16#issuecomment-436681617, https://github.com/airbnb/hypernova-node/pull/33#issuecomment-436679482); there’s no need to repeat the question.

I’ll try to make a release soon.

**Comment by ljharb** [comment]
Released.

**Comment by sPaCeMoNk3yIam** [comment]
Thanks a lot!
